title: "fluxbox"
subtitle: "The Window Manager"
copyright: "Copyright © 2001–2025, The Fluxbox Team."
languageCode: "en-us"
theme: "hugo-book"
pagination:
    pagerSize: 23
menu:
    after:
        - name: "Github"
          url: "https://github.com/fluxbox/fluxbox"
          weight: 100
#  main:
#    - name: News
#      url: "/news"
#      weight: 10
#    - name: Features
#      url: "/features"
#      weight: 20
#    - name: Download
#      url: "/download"
#      weight: 30
#    - name: Screenshots
#      url: "/screenshots"
#    - name: Help
#      url: "/help"
params:
    # theme: book
    BookSection: "*"
    BookComments: false
    fullWidthTheme: false
    centerTheme: true
    Toc: true
    Logo:
        logoText: "fluxbox"

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
    disqus:
        disable: false
    googleAnalytics:
        anonymizeIP: false
        disable: false
        respectDoNotTrack: false
        useSessionStorage: false
    instagram:
        disable: false
        simple: false
    twitter:
        disable: false
        enableDNT: false
        simple: false
    vimeo:
        disable: false
        enableDNT: false
        simple: false
    youtube:
        disable: false
        privacyEnhanced: false
